### ISSUE TITLE
[simple-modal:studio] Instructor View: Even larger please

### ISSUE THREAD

**Issue by WilliamMRose** [elmsln/issues#1064]

**Comment by WilliamMRose** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Instructor View: Even larger please](https://trello.com/c/Arm3fFnY/10-instructor-view-even-larger-please)

**Comment by btopro** [comment]
fixed in a local demo but studio requires all the moving pieces to fully verify. This is attacked in two ways right now:
- make the modal bigger (prev 75vw / vh) to 95vw / vh
- make the image inside the modal bigger (previously locked to 500x500)  to 95vw / vh

Need to ensure this doesn't disrupt any other buttons / capabilities but would make the viewable area as well as the default image significantly larger. Previous solutions only made the window larger but not impacting the media (issue is around the media itself)
- [ ] do a build
- [ ] test in stage
- [ ] take screen shot when successful and post back to the trello board
- [ ] close out here / move along in that process when we're good

**Comment by btopro** [comment]
need to allow for css var to make it leverage the full size of the window as well as support rotation without clipping
