### ISSUE TITLE
multiple-choice functionality issues

### ISSUE THREAD

**Issue by Peter12G** [elmsln/issues#1130]
- [x] revert multiple-choice to be array input based but keep the read / write to the lightdom
- [x] read in from lightdom for array data and build array on paint
- [x] don't render slot, only render the options in shadow
- [x] write back to lightdom as multiple options as if it was normal HTML (so drop the special type made)
- [x] opt for the character reporting feedback (and setting on fire if wrong)

**Comment by btopro** [comment]
this was highly usable until a refactor attempt in order to allow for dropping in anything and making it the option. Instead of this flexibility (which is now broken in HAX tho it works if hand written) let's just go back to using an array.
- [ ] revert multiple-choice to be array input based but keep the read / write to the lightdom
- [ ] read in from lightdom for array data and build array on paint
- [ ] don't render slot, only render the options in shadow
- [ ] write back to lightdom as multiple options as if it was normal HTML (so drop the special type made)
- [ ] 1st answer is assumed correct (think it still has this but verify)

**Comment by btopro** [comment]
![image](https://user-images.githubusercontent.com/329735/219801670-9caa743a-0303-4bf1-bbe2-4b5385a57f69.png)
