### ISSUE TITLE
[feature request]

### ISSUE THREAD

**Issue by Peter12G** [elmsln/issues#1563]
When hitting the "Change to..." button to change to a self-check, the self-check is unusable as there is no text box.

**Comment by btopro** [comment]
#1481 same issue. Some types don't lose their slot when it is empty while others do. Need to normalize this behavior.

**Comment by btopro** [comment]
tricky because it has 2 slots.... the 1st one forces there to always be content (empty slot in this case is actually the answer because who knows). So the issue is that the other slot goes blank. The additional issue is that this really doesn't need to support additional slotted material... but we've allowed it... so......... gotta think on this one

**Comment by btopro** [comment]
just dropping inplace editing for this. it doesnt make much sense and right now it'll forcibly activate the p tags where as spans are NOT directly focusable by design in the system. Now you modify them from the left panel and it shouldn't be an issue if there are different slot wrappers there or not. Now you can't delete them and can always add stuff to reclaim them, it just has to be from the left menu

**Comment by btopro** [comment]
@Peter12G this is out in production now, might need a refresh of assets / tomorrow
