### ISSUE TITLE
[bug] User report from HAX daemon

### ISSUE THREAD

**Issue by Peter12G** [elmsln/issues#1573]
Location: https://iam.hax.psu.edu/ptr5004/sites/aa100/new-item-4/lesson-9/page-3
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36 Edg/114.0.1823.58
OS: Windows - 8GB RAM - 12 cores
Screen: 1920x1080
Window size: 1920x961
Battery: 100%
Connection: 4g
Bug you experienced:

Quotation marks in multiple choice and possibly other places aren't formatting properly. It goes from " to &quot; 

https://psu.mediaspace.kaltura.com/media/Quotation+marks+formatting+issue/1_h5q0zxiu

**Comment by btopro** [comment]
Multiple choice sanitizes a text prop that needs to render back into the page unsanitized. Or, should be \" instead of htmlencoding the entity. Probably related to the fix for making page title work tbh

**Comment by btopro** [comment]
this is resolved in the next point release. The issue was that for security / stability of output, we encode:
```
<
>
&
"
```
in a forcible way so that it doesn't break the backend when parsing a well formed structure. Oversight on my part we were "fixing" the quote before the `&` which the fix includes the `&` character in it. So, you'd get `&amp;quot;` as the output where as `&quot;` is literally how HTML "escapes" the character so that it can be used in output that is wrapped in quotes itself.
