### ISSUE TITLE
Column Margin Spacing Suggestion

### ISSUE THREAD

**Issue by Peter12G** [elmsln/issues#1579]
Location: https://iam.hax.psu.edu/ptr5004/sites/aa100/new-item/lesson-1/case-study-2-chavin-de-huantar-and-andean-verticality-copy
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36 Edg/114.0.1823.67
OS: Windows - 8GB RAM - 12 cores
Screen: 1920x1080
Window size: 1920x961
Battery: 100%
Connection: 4g
Bug you experienced:

This isn't a real bug, it's more of a feature request. Currently, when things are put into columns, they don't line up in the margins with things that are not in columns. I tried moving things around in advanced and messing with margins manually, and it sort of worked. If I did it with the text, it cut off letters, if it is done with messing with the margins (left at -16) it lines up.

Could we default to margins in the columns being at -16 left (columns also can be manually adjusted on the right, but it doesn't look as bad because the text starts at the left) so it looks clean? I've attached screenshots demonstrating what I'm talking about.

This was done in Edge, but it also happens in firefox.

Image 1: Text doesn't align
![No Margin Adjustment](https://github.com/elmsln/issues/assets/123656933/c58fb37a-cea1-48b3-a791-1f069b9c2172)

Image 2: Paragraph adjusted to -16 on left. Parts of letters are cut off
![Margins Adjusted in Paragraph](https://github.com/elmsln/issues/assets/123656933/251ea003-eda2-427d-9067-c337edfe3ba0)

Image 3: Column format adjusted to -16 on left and -16 on right, aligns, is there a reason this can't be default?
![Margins Adjusted in Column Layout](https://github.com/elmsln/issues/assets/123656933/60947f38-aa2d-4a5a-be84-55873002c03a)

**Comment by btopro** [comment]
good report, better solution is to not influence padding/margin via magic so that it's just the default way of operating. Without having real content I won't know if this achieves the effect while still making it easy to work with editing wise (bc those margin / padding help w/ 'seeing' the blocks that exist for selection).

I faked it on this page via console modification and seems to line up nicely.
![image](https://github.com/elmsln/issues/assets/329735/80b81d35-08e8-44d6-a7b0-bb2f56e7c42c)
