### ISSUE TITLE
[haxcms] side menu needs labels / clarity

### ISSUE THREAD

**Issue by AndrewGearhart** [elmsln/issues#233]
As a user... I frequently mix up the buttons for "editing" ... 

Buttons such as:
- Edit page details
- Edit page content
- Edit site details

It would be helpful to have a collapsible menu to reflect the names beside the icons.

**Comment by btopro** [comment]
so like GravCMS does?
![image](https://user-images.githubusercontent.com/329735/82711845-91787d00-9c54-11ea-9fca-042689f66a69.png)
![image](https://user-images.githubusercontent.com/329735/82711886-a5bc7a00-9c54-11ea-9e6d-eec0e97a219b.png)

**Comment by AndrewGearhart** [comment]
Yeah, like that.

**Comment by AndrewGearhart** [comment]
Seems to be a pretty common thing that is happening. Jira does this as well

**Comment by AndrewGearhart** [comment]
![Screen Shot 2020-05-22 at 5 51 20 PM](https://user-images.githubusercontent.com/2346886/82712001-f633d780-9c54-11ea-9bbf-e711b5d05581.png)

**Comment by btopro** [comment]
https://www.apollographql.com/docs/07a52e1ffc14e4f245f94c9f620e143e/dev-tools.png another example.

**Comment by btopro** [comment]
* from back channel discussion *
a admin-side-menu type of element, made up of other elements would have to be built from scratch, use SimpleColors in order to allow throttling accent colors and what not. This is a good chance for a clean new menu area however we need mock ups / design comps to go off of so I'd like you to start there and post screen shots, ideas for it, links to other ones people have made, mock ups of what your thinking for it, etc.

After we get some agreement on how that should look / function / other concepts; then I want you to start moving into the implementation phase so you can try and go end to end with it from idea / issue all the way through to implementation of it as a stand alone menu structure. This would be a great contribution to our projects as people start using HAXcms on a more regular basis, but could also be constructed in a way that's a reusable piece as a web component (with other child components) for use in any project.

**Comment by btopro** [comment]
https://www.youtube.com/watch?v=zS0Kq81I5MU&feature=youtu.be @saracunn 's preliminary research / breaking down the UX issue happening here

**Comment by btopro** [comment]
#677 will handle this.
