### ISSUE TITLE
UX - Cannot drag to last item

### ISSUE THREAD

**Issue by AndrewGearhart** [elmsln/issues#266]
Within Hax ... you cannot drag an item to be the last item in the page. You can drag it to be the second to last item, then move the last item to be the second to last item... but you cannot drag any item to be the last item on the page.

**Comment by btopro** [comment]
Correct :) This is a fantastic example of a "small thing" that's a much bigger issue. It's all use the ::before selector to generate a dropable area (except Safari which cheats on this). I guess to solve this (which is a real issue) perhaps the entire hax-body area can have a ::after selector so that you can drop at the end.

**Comment by btopro** [comment]
fixed in next release
