### ISSUE TITLE
haxcms-site-editor-ui covers the page navigation on haxtheweb.org

### ISSUE THREAD

**Issue by nikkimk** [elmsln/issues#340]
haxcms-site-editor-ui covers the page navigation on haxtheweb.org

To fix this on all themes, you could add the following styles to haxcms-site-builder
-  position: relative;
-  margin-left: 50px;

**Comment by btopro** [comment]
you have some file in local storage bc of the service worker that is convincing your browser that it should show that menu. This functionality / fake demo has been removed in part to setup for #201 but also because we have a public demo that works fully and so we should incentive speed over a half ass demo :)


Now, figuring out how to kill the service-worker / appropriately refresh things... there are some issues associated w/ the service worker but not seeing it atm
