### ISSUE TITLE
[hax] Need to create a table

### ISSUE THREAD

**Issue by kat-wehr** [elmsln/issues#348]
Struggling to make a table - I eventually had to make it in HTML and paste into source code. See video? 
https://youtu.be/-YD-Uk6cZ9s

updated with page link - this is a fall course so please don't break it: https://courses.aanda.psu.edu/gd115/node/7

**Comment by kat-wehr** [comment]
Also probably related but I can't format the text for the table that I pasted into the source code.

**Comment by btopro** [comment]
#5 yeah there's no table functionality. There's a semi-busted table element but you currently must do this via HTML. @nikkimk would have to derail studio work to actually integrate the amazing editable-table element she made as we have no plans of making tables "content editable" without the UX pattern she made. There's a ton of thought behind HOW to do this and examples, it's more an issue of making a way to integrate it effectively so that tables can be replaced / wrapped, temporarily with the editable-table tag, then workflow to make the editable-table tag go away and the modified table remain. (this is not a blame response it's reality / state of where we're at with it).

**Comment by btopro** [comment]
next version now has this
