### ISSUE TITLE
As a user I want to be able to add links without a popup.

### ISSUE THREAD

**Issue by onelittlebecca** [elmsln/issues#4]
Proposed Solution:
Consider using the same field like the alt field for images. It just appears above/below the link and a user can edit it on the spot and it is inline.

**Comment by btopro** [comment]
@nikkimk when you wrap up your current Eco work do you think you could take this one? I know you have your absolute positioning thing working in your text editor. I wonder if you could replace how the current one works in HAX for just the link button so that we can inch closer to your editor + you getting more in the weeds of how things are stitched together in HAX.

**Comment by btopro** [comment]
edit no longer requires pop up. @nikkimk 's text editor has this ability she just needs to port it to this one

**Comment by btopro** [comment]
new version of the editor has this in its priority map / is being worked on actively.
