### ISSUE TITLE
simple-fontpicker component

### ISSUE THREAD

**Issue by nikkimk** [elmsln/issues#44]
- Minimum: loads fonts defined in the site
- Enhancement: queries Google Fonts for a list

**Comment by btopro** [comment]
picker exists; needs implemented and this issue is too old to maintain without detail. It'll show up in future UX reports and there are some related issues associated with #654 that would touch on this automatically (themes supplying a range of acceptable font families instead of us heavy handed dropping a ton of fonts in and hoping for success)
