### ISSUE TITLE
Make Atom components available

### ISSUE THREAD

**Issue by WardinT** [elmsln/issues#472]
For content creators, there should be basic elements like buttons, icons, etc. available.
More advanced components could be created by nesting, in an ideal world, these could be saved for reuse on a per-user or - with sufficient rights - per-site basis.

**Comment by btopro** [comment]
#40 and some other work is planned around saving chunks of templates for later re-use. The atoms you mention are all available but the CDNs we provide simply build these out ahead of time but do need a better way of finding them. They are mixed in w/ the rest of our web component library as everything is "just" a web component, and then happens to work with HAX.

https://cdn.webcomponents.psu.edu/cdn/wc-registry.json (use a json viewer) demonstrates everything we have out there. HAXcms has all of them built in since everything builds for HAXcms and then happens to work everywhere else because of how our tooling cascades. Here's some example ones for now.

```json
{
    "@lrnwebcomponents/a11y-gif-player": "^3.0.0",
    "@lrnwebcomponents/aframe-player": "^3.0.0",
    "@lrnwebcomponents/citation-element": "^3.0.0",
    "@lrnwebcomponents/hero-banner": "^3.0.0",
    "@lrnwebcomponents/image-compare-slider": "^3.0.0",
    "@lrnwebcomponents/license-element": "^3.0.0",
    "@lrnwebcomponents/lrn-aside": "^3.0.0",
    "@lrnwebcomponents/lrn-math": "^3.0.0",
    "@lrnwebcomponents/lrn-table": "^3.0.0",
    "@lrnwebcomponents/lrn-vocab": "^3.0.0",
    "@lrnwebcomponents/lrndesign-blockquote": "^3.0.0",
    "@lrnwebcomponents/magazine-cover": "^3.0.0",
    "@lrnwebcomponents/media-image": "^3.0.0",
    "@lrnwebcomponents/meme-maker": "^3.0.0",
    "@lrnwebcomponents/multiple-choice": "^3.0.0",
    "@lrnwebcomponents/person-testimonial": "^3.0.0",
    "@lrnwebcomponents/place-holder": "^3.0.0",
    "@lrnwebcomponents/q-r": "^3.0.0",
    "@lrnwebcomponents/self-check": "^3.0.2",
    "@lrnwebcomponents/stop-note": "^3.0.0",
    "@lrnwebcomponents/task-list": "^3.0.0",
    "@lrnwebcomponents/video-player": "^3.0.0",
    "@lrnwebcomponents/wave-player": "^3.0.0",
    "@lrnwebcomponents/wikipedia-query": "^3.0.0"
}
```

I've opened an issue #476 so that we add this into the package.json so it's easier to find. An aspect of the settings page in HAX for Drupal/other CMSs is that it loads off the wc-registry.json and tells you about the element. So another thing you could do is point to the PSU or WaxaM CDN, hit save, then look at the elements page to see what is available there and find ones you want (which should have details as to how to get the NPM related asset). Add those to your build and then you'll have your own custom build w/ just the things you want (a common complain is having atoms that people don't want to use bc of how many we're making for various use-cases which I get).

**Comment by WardinT** [comment]
I don't yet get it: My perception is that a webcomponents repository - be it local or via CDN - offers a number of components to be used which for PSU seems to be the wc-registry.json you copied in. From there, I select which ones I want to show up in the add content section. Shouldn't building the unbundled repository then have included all components of the wc-registry.json you linked in?

So I simply wait for the PSU repository to show the atoms for selection?

**Comment by btopro** [comment]
our worldview:
- everything is a web component everywhere all the time no matter what. We have 400+ web components our team has made at this point; all little atoms or atoms made of other atoms.
- unbundled-webcomponents is for shipping web components to any device, deployment or application
- HAX happens to leverage this same information in order to power itself
- You can choose to do a build with all the assets that we build with for our CDNs, or just the ones you want
- at the moment, we only ship directions for the bare minimum given that those going this route are probably making their own assets / want to run it on their own

As an example;
You can do `yarn install @lrnwebcomponents/simple-cta` and get a call to action button in your build. The call to action button has wiring for hax, therefore on the settings page it'll show up and you can select to include it in your editor.

If you think it should have all the atoms we'd have to make a tooling change in order to automatically manage the package.json file that's provided as an example for that repo (which people use for non-hax projects as well). A more likely scenario is we take a whole ton of the most common ones and we include those in the example so that people get an expected starting point as you are describing.

**Comment by WardinT** [comment]
What if you provide a checkbox "Show all (including atoms)" on the HAX configuration screen?

**Comment by btopro** [comment]
@heyMP and I have made prototypes in the past doing this from a different screen. It can be made, it's just not super useful information since you can get non-hax capable web components anywhere. It might make it more visible just how big the concept is so it's not a bad idea, would just need to be integrated appropriately. We've been wanting a way of making it possible for people to wire up other elements to HAX via a UI so maybe a different panel for like non-HAX capable atoms.

**Comment by WardinT** [comment]
I wasn’t thinking outside the HAX universe. Atoms should also be HAX-capable.

**Comment by btopro** [comment]
I mean theoretically they are. If your calling "web components" Atoms here, then yes, they are. You can technically load in any customElement but without a haxProperties defintion on the class'ed element it will just guess what attributes to put into the editing interface so it's got limited UX ability.

https://www.npmjs.com/search?q=keywords:haxtheweb

**Comment by btopro** [comment]
apparently we have `77 packages found` for this keyword. Guessing here but probably 50 we use in production, 10 are older ones that work but we dont use, 15 we haven't implemented yet and 2 are hax itself. Guessing cause I rant through and did it quickly but installing almost any of these will then show up as the things we make available.

**Comment by WardinT** [comment]
If I understand correctly, the "wiring for HAX" is in the way of inluding whole libraries from vaadin or htmlelements. Still I am convinced that collections like these need to be available for "ordinary" editors in the "Add content" dialog.

**Comment by btopro** [comment]
hmmm no I disagree but I think it's cause we're missing each other in the language we're using to describe.

## Web components
a new HTML tag that works anywhere and is powered by javascript. This works anywhere and is not HAX related. Cross browser capable.

## HAX
An editor that manipulates anything inside of it that is HTML. Web components are HTML, so it can manipulate them. Also HAX is written using the web components standard and so it also gets cross browser benefits.

"wiring for HAX": any webcomponent that implements `static get haxProperties()` and delivers our schema will be able to deeply integrate w/ HAX editor UI.

## Example
- video-player is `@lrnwebcomponents/video-player` and can be used on any website. For example it's on the https://hax.camp/ homepage.
- video-player is a complex implementation of `haxProperties` but is still one for sure https://github.com/elmsln/lrnwebcomponents/blob/master/elements/video-player/video-player.js#L119-L391
- vaadin elements like vaadin-button, do not implement haxProperties, though they could, and their API is geared toward developers

So we might make `simple-cta` for a "call to action" button which happens to leverage vaadin, but it provides a semantic named element from the end user's stand point so that they see `<simple-cta>` in the DOM.

**Comment by WardinT** [comment]
You are absolutely right: Having a common wording is the necessary starting point. Please bear in mind that I have the Drupal hax module with its editing panel in mind.

What I am striving for from a Drupal editor's perspective is having atoms (basic elements) and components (made up of pre-configured nested atoms) avaliable in that editing panel for dragging into the canvas. Only in very rare exceptions, my editors are supposed to write html.

I have started filling a demo page (https://d9.mein-tier-mit-dir.de/node/9) with what I have found on my site. This is not yet finished but meant to make clear the direction I'm heading.

**Comment by btopro** [comment]
appstore spec expansion allows dictating the wiring that ships w/ elements from the backend.This means things without haxSchema can be wired up after the fact. Doesn't speak to their UX but is possible. Opening sub-issue about documenting this spec enhancement that was in the last release.
