### ISSUE TITLE
Grid-plates do not show on old iPads (ES5)

### ISSUE THREAD

**Issue by WardinT** [elmsln/issues#473]

**Comment by btopro** [comment]
please include screenshots (sorry I know we've transitioned issues queues) for this as I've tested on ipad (emulated) and it's worked previously. I don't doubt this is the case just trying to reverse engineer what the issue is. We also have some work on positioning prior to the web component rendering which might help in older browsers as well.

**Comment by WardinT** [comment]
![Grid on PC](https://user-images.githubusercontent.com/24524242/104488215-59042580-55ce-11eb-8d8f-06e7590dbc4c.JPG)
![Grid on iPad](https://user-images.githubusercontent.com/24524242/104488238-5e617000-55ce-11eb-9ee4-85177cd9f018.JPG)
You may want to have a look at the public page at https://d9.mein-tier-mit-dir.de/node/8

**Comment by btopro** [comment]
grid plates and overall es5-esk support is about at it's apex. It should work in what we have in the coming release but if it doesn't we won't be able to support it because of how much our focus is on evergreen traffic and it falls back to still be functional
