### ISSUE TITLE
[grid-plate] Rendering of grids with unequal column widths

### ISSUE THREAD

**Issue by WardinT** [elmsln/issues#474]
Width is only changed when "Diable responsive" box ist checked.
Reported for 2-column-2/3-1/3 grid.

**Comment by btopro** [comment]
@nikkimk might be able to comment on this more but in my personal work w/ HAX as the authoring experience I always disable responsive columns. My guess is that the break points are set relative to a very large device but I'm not positive. If your looking for some example content out there here's my online course that uses hax / grid plates and what not https://oer.hax.psu.edu/bto108/sites/ist210/

**Comment by WardinT** [comment]
I noticed somewhat unusual breakpoints pre-set in the grid-plate component. From Bootstrap, I normally see these:

// Extra small devices (portrait phones, less than 576px)
// No media query for `xs` since this is the default in Bootstrap

// Small devices (landscape phones, 576px and up)
@media (min-width: 576px) { ... }

// Medium devices (tablets, 768px and up)
@media (min-width: 768px) { ... }

// Large devices (desktops, 992px and up)
@media (min-width: 992px) { ... }

// Extra large devices (large desktops, 1200px and up)
@media (min-width: 1200px) { ... }

Still I don't understand the "Disable responsive" checkbox: If left unchecked, the grid seems not to change when column layout is changed from the dropdown. If it is checked, columns change and adjust to varying screen sizes, which I would call responsive... Should it just be named "Enable responsive"?

**Comment by btopro** [comment]
The breakpoints @nikkimk can speak to and we probably need a way of swapping those out via global setting #212 anyway. As for the checkbox name that is certainly something we need to discuss. The default behavior is to be screen responsive at the column level. If you disable responsive, they maintain their 1-1-1 layout (or which ever selected). If that is NOT set, they will collapse into other layouts when on mobile / other breakpoints. The user expectation seems to be that a grid will actually appear as a grid in the majority of scenarios; either that or our breakpoints need changed for some rationale beyond where they are currently.

**Comment by WardinT** [comment]
I editing mode, the columns do not change when "Disable responsive is unchecked, see screenshots
![Wide-and-narrow responsive](https://user-images.githubusercontent.com/24524242/104494372-aab0ae00-55d6-11eb-85bb-12c2104e69ce.JPG)
![Wide-and-narrow non-responsive](https://user-images.githubusercontent.com/24524242/104494389-b00df880-55d6-11eb-95d1-5f67e19c7419.JPG)

**Comment by btopro** [comment]
try dragging the window in. The ones without the checkbox will start to respond and shift around while the disabled ones will maintain their grid even if they just adjust in size relative to the window

**Comment by WardinT** [comment]
But then isn’t the first set rather adaptive than responsive? I am always thinking of responsive elements as shrinking and growing corresponding to screen size. If elements change their general representation, I‘d not use the same term.

But the important thing irrespective of how to call them: With the checkbox not ticked, the proportion of the columns does not change while they are still columns: 2/3-1/3 is still shown as 1/2-1/2.

**Comment by WardinT** [comment]
Just noticed the same behavior with two equal columns.

**Comment by btopro** [comment]
https://github.com/elmsln/issues/issues/763 related

**Comment by rickhumphries** [comment]
Just wanted to add a couple of thoughts on this having played around with it a little. The 'disable responsive' checkbox was a bit confusing for me at first too as I also expected the default behaviour to be that that if I've using a grid system the columns will stack on top of each other on the smallest screen sizes. However, that's a minor point and I can see what the option allows for so that's fine.

The other confusion for me when setting this up came because a mixture of two things. First, as @WardinT pointed out, the default breakpoints set are a little high, and second this is made to seem worse because the `<grid-plate>` takes the width of the parent container (I think) to determine when to break, rather than the width of the screen. So it doesn't act in line with a usual media query and can also be affected by other responsive elements on the page (such as a menu shifting from left to the top of the page for example). I reset my breakpoints to `sm=300 md=800 lg=1000 xl=1500` which seems to be relatively OK.

One limitation that I can see currently compared to other grid systems is that you can't select more than one different grid layout depending on different breakpoints. The grid layout that's chosen therefore will only apply to medium widths and higher and will stack only at 'small'.

Final comment is just from a html structure point of view but definitely open to discussion on this one. HAX will apply the `slot=col-x` to every single element whereas I think it's a bit more manageable to structure it with a wrapping <div> like this:
```html
<grid-plate data-hax-grid="" layout="1-1-1" responsive-size="lg" breakpoint-sm="300" breakpoint-md="800" breakpoint-xl="1500" role="textbox" breakpoint-lg="1000">
  <div slot="col-1">
    <p>TEXT CONTENT COLUMN 1</p>
  </div>
  <div slot="col-2"> 
    <p>TEXT CONTENT COLUMN 2</p>
  </div>
  <div slot="col-3">
    <p>TEXT CONTENT COLUMN 3</p>
  </div>
</grid-plate>
```

I know @nikkimk has opened an issue about reimagining grid-plate anyway so just wanted to add my thoughts in case it's useful for informing that.
