### ISSUE TITLE
[meta] Consider a print-this superclass, button

### ISSUE THREAD

**Issue by nikkimk** [elmsln/issues#513]
- superclass could be used to print just the item what is targeted by id
- could to be able to take a print-styles array
- stand-alone button extends superclass and could be used in other component's UI

**Comment by btopro** [comment]
interesting concept. Would this be more tying into a singleton that manages the notion of "print this target" while the superclass is mostly hooking in some baseline styles / open in a new window the target sorta logic? I'd have to see this in action to really grep it I think but this sounds like a powerful idea.

**Comment by btopro** [comment]
because of limitations in the way shadowRoots work this sadly is not possible and full documents need rendered. The video-player's transcript printer has no custom elements in it or it would run into this issue. After talking w/ lit people the only solution to #710 was to open a new window w/ a mode that re-rendered the entire site but in a "new theme" which stripped everything else away.
