### ISSUE TITLE
[hax] [elmsln] Clicking 'cancel' in the HAX editor wipes all content on the page

### ISSUE THREAD

**Issue by rickhumphries** [elmsln/issues#528]
When clicking the 'cancel' button which I've done a few times thinking it might just cancel my changes, it actually strips all the content from the page.

You can then accidentally clicked 'Save' from the 'ELMSLN' menu options and it will save with no content.

http://g.recordit.co/xf0MhYUSq3.gif

**Comment by btopro** [comment]
in master?

**Comment by rickhumphries** [comment]
Just added a video - this isn't on master yet

**Comment by JackWillDavis** [comment]
Can confirm this is still happening on master branch

**Comment by btopro** [comment]
does it wipe it and save or does it just wipe it and sorta leave you in a "what do I do now" state where if you go back to view the content it's fine. If this is the case, maybe hitting cancel should take you back to the `view` state of it since it's effectively the same as hitting view / leaving the page. HAX clears the body area as to not load in something bad / different from what it was originally handed so I think this might be better served listening for the `hax-cancel` event in ELMS:LN / Drupal and redirecting back to view.

What do you think @JackWillDavis does this sound like it would solve the issue?

**Comment by rickhumphries** [comment]
> does it wipe it and save or does it just wipe it and sorta leave you in a "what do I do now" state where if you go back to view the content it's fine

@btopro yep exactly that. 

Agree that hitting cancel should just redirect you back to the view state then that eliminates any possibility of accidentally wiping all your content. That would solve it

**Comment by btopro** [comment]
In looking at it, this is actually an issue w/ the cms-hax tag which can handle this via the `redirect-location` attribute. On cancel you have to confirm, if you confirm, then I'll just redirect to that location :)

**Comment by btopro** [comment]
next build should include this though we are waiting on @nikkimk 's HAX revision before we move forward w/ that.
