### ISSUE TITLE
[elmsln] Refresh issue on course pages

### ISSUE THREAD

**Issue by JackWillDavis** [elmsln/issues#530]
If visiting a course page with a trailing `/`, the page will keep refreshing itself as soon as it loads in. For example:

`courses.example.co.uk/testcourse/node/2/`

Will cause the page to constantly refresh whereas the link below doesn't:

`courses.example.co.uk/testcourse/node/2`

This is happening on the master branch of ELMSLN.

**Comment by btopro** [comment]
@JackWillDavis I made a commit but I have to do a full build to see it in staging to know if it works for this issue so it isnt tested. I believe it'll work though as it's related to the route ending in a `/` but the way the split happens to figure out what node we're on it is assuming this is a node id / numeric, otherwise it would brick.

**Comment by JackWillDavis** [comment]
Ah nice one, thanks a lot!

**Comment by btopro** [comment]
@JackWillDavis you'll need to do a build locally to confirm this fix; otherwise we'll have to wait a bit until a build is safe for production as replace-tag and @nikkimk hax rewriting are actively being pursued and master is not currently stable (even tho it largely is, I just mean it's still influx)

**Comment by JackWillDavis** [comment]
Yeah, I'll test it this afternoon if I get a mo and let you know how if it's sorted.

**Comment by JackWillDavis** [comment]
Thought I could test the fix quickly now actually. Yeah, that's stopped the page from repeatedly refreshing now. Thanks!
