### ISSUE TITLE
Add option to disable fast-forward/seek forward to a11y-media player.

### ISSUE THREAD

**Issue by nikkimk** [elmsln/issues#55]
Ultimately the goal would be to pair this with branching/interactive and re-enable once all branching questions are complete.

**Comment by btopro** [comment]
- add variable for disable-ff button
- add variable for disable-seek button

This would then lead to a pattern of disabling other aspects of video / events bubbled off when state changes of these

**Comment by Griffin-Sullivan** [comment]
I'll take this, and maybe add to it barring time, the turn off transcript and dragging.

**Comment by btopro** [comment]
@Griffin-Sullivan look into a11y-media-player which sits behind `video-player` doing most of the heavy lifting visually and functionality wise. We'll want this to be a boolean flag that disables parts of the UI but then also be something that could be in the haxProperties advanced schema for video-player so that it can leverage this on the authors end. For example, a training author does not want people to be allowed to skip ahead in media for legal purposes.

**Comment by btopro** [comment]
@Griffin-Sullivan PR'ed this so now the disabling searchable transcripts flag which is its own new issue
