### ISSUE TITLE
[hax/ux] Task B: Small article about your favorite activity / sport

### ISSUE THREAD

**Issue by btopro** [elmsln/issues#593]
Create a page of text about your favorite animal / sport / activity. In this page include:
- a heading
- a paragraph of text
- Bulleted list with links to supporting articles

**Comment by caitlinnorse** [comment]
Task B by Donal Harnett:
1.	Logfed into website
2.	Clicked new site 
3.	Named it “Favorite Activity”
4.	Clicked favorite activity from selection board
5.	Went to the left and clicked the edit pencil
6.	Clicked block button and it appeared
7.	Typed in “I like to watch TV”
8.	Has trouble finding how to add a heading
9.	Went to blocks
10.	Clciked markdown button
11.	Tries to edit added content
12.	Went to blocks
13.	Clicked Headings 2
14.	Went to title
15.	Wrote ‘Favorite activity”
16.	Moves block so that it Is the title
17.	Deletes original content block
18.	Googles “TV guide”
19.	Clicks “Los Angeles TV listings”
20.	Goes to blocks
21.	Adds a horizontal line
22.	Is confused about what was added
23.	Deletes the line
24.	Scrolls through blocks
25.	Adds a task list
26.	Creates a paragraph
27.	Hovered over the paragraph that was created
28.	Changed the paragraph to “bulleted list”
29.	Pasted in link
30.	Googles Netflix
31.	Adds that to his list
32.	Accidentally double clicks and creates a paragraph
33.	Deletes paragraph
34.	Saves Page

**Comment by Aero427** [comment]
![image](https://user-images.githubusercontent.com/78039921/113029673-b2560c80-915a-11eb-8191-39bb87754fb9.png)

**Comment by NovasKnowledge** [comment]
1. Clicked new page
2. Pencil button on side
3.  New page, trying to figure out page
4. Finds format button and nothing happened when she hit it
5. Struggling how to figure out to page
6. Ended up adding a paragraph to the page
7. Hit blocks on the side and that's how you add in different headings for paragraphs
8. Bulleted lists in format button at top of the page
9. Still playing around with the page to figure out what to do
10. Copy and pasted something into the paragraph and it did not work.
11. Clicked on the box to start typing paragraphs
12. Adding another box to add the same things.
13. Very far right box is a delete button
14. If you hit enter it creates a new box without clicking on adding a new box.
15. Added link about hiking on the page
16. Hit blue button on side to save page
