### ISSUE TITLE
[hax/ux] Task D: Search and find assets

### ISSUE THREAD

**Issue by btopro** [elmsln/issues#595]
Build a page of resources using references to existing resources, without leaving the page. Write a small article about Space travel:
- Embed media from NASA
- Embed an article from wikipedia

**Comment by hvk5388** [comment]
Search and find assets
Uses simple blog
Can’t figure out which card is his
They all have the same picture
Has to make a page because he picked blog
Edit content
Imbed media
Nasa is just there
Add picture of atlantis spaceship
Unsure of how to type a paragraph
The start of the paragraph is hidden behind the editor
Has to collapse
Add wikipedia
Not the page source
Under blocks
Wikipedia article
Why is it in spanish??
Licensing is in english
This article does not look correct
Uses nasa instead of space
Save
Edit page content keeps duplicating everything
