### ISSUE TITLE
[hax] tray / mobile UI clean up

### ISSUE THREAD

**Issue by btopro** [elmsln/issues#677]
## In mobile mode
- [x] UI sticks to top, the left/right connotation just changes the size slightly / doesn't make sense and the labels don't show so there's no reason for the button currently
- [x] hit button to send UI tot he left side, then go mobile, then hit any option and you get this screenshot
![image](https://user-images.githubusercontent.com/329735/117457462-3ac48b80-af17-11eb-971f-65e32f295a12.png)
- [x] cancel button w/ the hover intent to cancel operation is hidden while tray is collapsed (z-indexing / overflow issue)

## normal full screen
- [x] Move left maybe should be "Move Menu left" on hover or something. Single word "left" looks weird
- [x] spacing of icon to text looks too crowded. Maybe slightly smaller icon or better padding
- [x] Media button -> URL's "browse..." button is crowded / CSS odd
- [x] Cancel on a tray menu that's open does not animate it closed so it sorta hangs there, then disappears
- [x] text color on the Help / Tour is black on blue while cancel is white. On tray panels it's White text on Blue and the X is a white button w/ Black X
- [x] I'd order these as Save, Cancel, undo, redo, edit, media, blocks, outline, source, settings, help, left

## high priority / blocking issues
- [x] link button in text menu is a browser level `prompt` instead of the link dialog that your table editor does so this behavior is inconsistent (table is way better obviously!)
- [ ] Make a table in context and then click away. Table shows, then after a delay it re-renders the table editor so it's not possible to see how it'll actually look without the editor on it (error in console might be causing it: `ReferenceError: insert is not defined` editable-table-editor-rowcol.js:204 )
- [x] when to the left, the tray is clipping the UI even when collapsed / closed (this is also happening on the right just less noticible bc no content there in the demo)
- [x] cancel button intent overlaps the options; maybe make it fly out to the left of it or click and then it turns into "Sure?" or something. I like the double confirmation (delete can in the page though added an option that if you double click it'll do the delete and skip the confirmation bc it was getting annoying to users in class)

## low / medium priority
- [x] any screen resizing / repositioning the options animate into place / jump around
- [x] clicking the menu button a 2nd time should collapse the menu (just like if hitting the cancel)
- [x] Source being the only thing to open in a modal now feels a bit odd. Thoughts on this rendering the size / shape of the actual `hax-body` area so that it's like you are editing the source in place (ala dreamweaver). Then the menu options of this element could be in-context / top of the bar thing to provide consistency w/ the other way of editing source of individual things in context.
- [x] toggling to new item in the page doesn't open the edit menu which could be confusing. Also no icon association to the thing selected (I think there once was in the edit panel at one time)

**Comment by nikkimk** [comment]
Status as of [my latest push to nikki branch](https://github.com/elmsln/lrnwebcomponents/commit/df0ebba9dcf973143a7e53b7f5a716ab2cac463e): 

> ## In mobile mode
> * [x]  UI sticks to top, the left/right connotation just changes the size slightly / doesn't make sense and the labels don't show so there's no reason for the button currently
> * [x]  hit button to send UI tot he left side, then go mobile, then hit any option and you get this screenshot
>   ![image](https://user-images.githubusercontent.com/329735/117457462-3ac48b80-af17-11eb-971f-65e32f295a12.png)
> * [x]  cancel button w/ the hover intent to cancel operation is hidden while tray is collapsed (z-indexing / overflow issue)
> 
> ## normal full screen
> * [ ]  any screen resizing / repositioning the options animate into place / jump around
> * [ ]  when to the left, the tray is clipping the UI even when collapsed / closed (this is also happening on the right just less noticible bc no content there in the demo)
> * [ ]  cancel button intent overlaps the options; maybe make it fly out to the left of it or click and then it turns into "Sure?" or something. I like the double confirmation (delete can in the page though added an option that if you double click it'll do the delete and skip the confirmation bc it was getting annoying to users in class)
> * [ ]  clicking the menu button a 2nd time should collapse the menu (just like if hitting the cancel)
> * [x]  spacing of icon to text looks too crowded. Maybe slightly smaller icon or better padding
> * [ ]  toggling to new item in the page doesn't open the edit menu which could be confusing. Also no icon association to the thing selected (I think there once was in the edit panel at one time)
> * [x]  Move left maybe should be "Move Menu left" on hover or something. Single word "left" looks weird
> * [x]  I'd order these as Save, Cancel, undo, redo, edit, media, blocks, outline, source, settings, help, left
> * [ ]  Source being the only thing to open in a modal now feels a bit odd. Thoughts on this rendering the size / shape of the actual `hax-body` area so that it's like you are editing the source in place (ala dreamweaver). Then the menu options of this element could be in-context / top of the bar thing to provide consistency w/ the other way of editing source of individual things in context.
> * [x]  Media button -> URL's "browse..." button is crowded / CSS odd
> * [x]  Cancel on a tray menu that's open does not animate it closed so it sorta hangs there, then disappears
> * [x]  text color on the Help / Tour is black on blue while cancel is white. On tray panels it's White text on Blue and the X is a white button w/ Black X
> * [ ]  link button in text menu is a browser level `prompt` instead of the link dialog that your table editor does so this behavior is inconsistent (table is way better obviously!)
> * [ ]  Make a table in context and then click away. Table shows, then after a delay it re-renders the table editor so it's not possible to see how it'll actually look without the editor on it (error in console might be causing it: `ReferenceError: insert is not defined` editable-table-editor-rowcol.js:204 )

**Comment by nikkimk** [comment]
Some of the blank ones are more involved or I created other solutions that may deem them unnecessary.

Are the following still issues:
- any screen resizing / repositioning the options animate into place / jump around
- when to the left, the tray is clipping the UI even when collapsed / closed (this is also happening on the right just less noticible bc no content there in the demo)

"toggling to new item in the page doesn't open the edit menu which could be confusing. Also no icon association to the thing selected (I think there once was in the edit panel at one time)"
- Automatically opening the edit menu may no longer make sense, given that the user may want it to be collapsed, especially as we get into editable layouts. 
- Having an icon that constantly changes in the menu can be equally confusing, especially if the gizmo icon is the same as one of the icons selected for the menu
- Instead I added a contextual edit button to the toolbar so that users can see exactly which item they are editing and decide whether or not they want to expand it

Looking at these is going to take a lot more time. Should we switch to Studio and come back to them: 
- link button in text menu is a browser level prompt instead of the link dialog that your table editor does so this behavior is inconsistent (table is way better obviously!)
-  Make a table in context and then click away. Table shows, then after a delay it re-renders the table editor so it's not possible to see how it'll actually look without the editor on it (error in console might be causing it: ReferenceError: insert is not defined editable-table-editor-rowcol.js:204 )
- not listed, but there are still some non-grid editable layout related things that will take time
- not listed, but there are still some things that will require a big refactor to make adding new blocks in context

-

**Comment by btopro** [comment]
closing out as this is why we have a 4.0.0 release and everything I keep looking at in the list was fixed except table editing which is in the works
