### ISSUE TITLE
As a user I want to be able to add and/or remove columns.

### ISSUE THREAD

**Issue by onelittlebecca** [elmsln/issues#7]
Really this is about removing columns. Adding columns to the grid plate is not an issue, but there are no options to remove columns and if you select the "remove grid plate" option, then the whole grid plate removes and removes any content already in columns in said grid plate. SUPER frustrating.

Proposed Solution:
- [x] Just like there is an ability to add a column, we need one to remove.
- [x] Hide the hidden columns that appear below.
- [x] when removing a grid plate, keep the contents and break them out of the grid instead of deleting

elmsln/lrnwebcomponents#182

**Comment by btopro** [comment]
Now there's a + and - button which are stacked. Based on the number of columns they will be enabled / disabled. Also extended it to 6 columns since that's technically what they can go up to.
some screenshots of the start of this solution:
![image](https://user-images.githubusercontent.com/329735/73880719-eec6fa80-482c-11ea-997e-d1cbd72aadb1.png)
![image](https://user-images.githubusercontent.com/329735/73880750-fd151680-482c-11ea-8f1a-24ab1530f336.png)

**Comment by btopro** [comment]
start of grid plate delete with `-` buttons which then break out of the grid. Issue currently is that not all of the elements come back out; just the ones in the 1st column. Hidden columns are smaller and less in your face though still need to be there currently in the event any content is in them. Another possible solution might be that they are there but can't be drag and drop and then stuff in them has lower opacity or something. Some way of indicating that the items need to be placed in a column because it no longer exists.

**Comment by btopro** [comment]
better styling on things not on the grid. Also better clean up w/ grid going away but still weird children being removed in not the same number as are in the grid before (when deleting). Need to look more at whats up there..

**Comment by btopro** [comment]
Can now add and delete grid columns in context, hidden columns are less ridiculous looking, drag and drop zones are better color and solid outline instead of a dashed (more professional looking already in that area), and when you delete the columns it won't delete the contents.

However, if you delete the grid using the trash can it will kill everything because that's sorta the point of deleting the whole thing. If delete gets moved over ala grapes style then it'll be even more obvious hopefully that it's removing what your working on vs just adding / subtracting the grid.
