### ISSUE TITLE
Rescue orphaned slots that are not in a layout's template.

### ISSUE THREAD

**Issue by nikkimk** [elmsln/issues#760]
**The problem**
- Any content in a slot that is not part of its parent's template is **orphaned**, or hidden so that we can't fix it more move it to a slot that is templated.
- If we used Change To... on a grid and the grids we could have orphaned slots because the new template has different slots.

**Proposed Solution**
Automatically map orphaned content to a slot that does exist in the grid's config. Ideally it would try to match based on the slot config in the grid's haxProperties.

1. Find a slot with a matching slotWrapper.
2. Find a slot that has a slotWrapper that the current content could be converted to (eg., `<p/>` to `<div/>` or `<a11y-gif-plater/>` to `<img/>`).
3. If there is no way to automatically recuse the orphan, have some indicator that any remaining orphan slots exist and interface for reassigning this content.

**Comment by btopro** [comment]
I like the proposed solution. Another possible series of options along those lines:
- if a generic slot is detected, force the items into the generic slot
- if there isn't, detect the 1st slot or mark some kind of priority slot in the API and force things into this one
- if these can't be done, take the items and actually just inject them as pieces BELOW the newly converted design. This way the parts are still there for the user to either delete or put back into place

While I like the idea of a holding area of sorts I wonder if that concept is a bit too developer central where our users might take like 3 lines of input, convert it to something with only 2 lines and then assume the 3rd line would still remain, just not part of the new design. This gives them the ability to fix manually instead of us forcing a peg into the wrong shape (analogy).

**Comment by btopro** [comment]
Forgot; we've also had discussions in the past of like #734 and the notion of defining a type of "HTML primitive" that matches. Another similar concept is that haxHooks supplies a `progressiveEnhancement` which fires when ripping into the DOM / saving the body of content. meme-maker uses this so that even if you didn't have the meme you'd still get something that represents it for SEO. I wonder if there's some way of leveraging this information as well to map slotted details / find things that didnt match up in the conversion (just more thinking outloud).
