### ISSUE TITLE
[page-break] Add support for author only comments attached to page

### ISSUE THREAD

**Issue by nikkimk** [elmsln/issues#781]
A web component that only displays within edit mode that can be used to leave notes for future revisions. For example

```
<edit-mode-only from="nikkimk" to="nikkimk">Note to self: fix this.</edit-mode-only>
<edit-mode-only from="id" to="faculty">What do you think about making this section a video?</edit-mode-only>
```

Caveat, while these won't appear in the css, they are still part of the page code. Otherwise, we'd have to store the actual messages somewhere.

**Comment by btopro** [comment]
comments could be forced to be text editor and `nodeType === 8 ` will be a valid match internal to the element if we really end up needing something like that. Still there might need to be some UX implication in the editor itself (kind of like how page-break has special integrations) in order to ensure that users actually bother to use it as opposed to writing **HEY PUT THE THING HERE IN THIS AWESOME YELLOW TEXT** like many do now.

**Comment by btopro** [comment]
Page-flag added
