### ISSUE TITLE
HAX Editor not recognising content

### ISSUE THREAD

**Issue by rickhumphries** [elmsln/issues#914]
We have some pages where I've edited something with HAX, saved then gone back to edit but all the content 'disappears'.

E.g. page looks fine:
![image](https://user-images.githubusercontent.com/4973810/145309534-7a930653-7674-4d2e-8551-2e2e4284790f.png)

Then in HAX...
![image](https://user-images.githubusercontent.com/4973810/145309580-29421b47-a4e0-4242-bc6b-547dffa581dc.png)

The console messages say this...
![image](https://user-images.githubusercontent.com/4973810/145309627-23d8791d-d627-4fb1-a72f-dd5e83f62230.png)
The first two messages do show up on pages that work fine, whereas the 'TypeError' is the common displays on all the pages we have an issue with so I think it's related to that.

**Comment by btopro** [comment]
hmm.. that dom exception might be the culprit. can you DM me the raw HTML from HAX as to what that page should be? It's possible that the entire document is wrapped in a div and that's goofing it up too. I have seen this but not in a long time (we also don't actively monitor this form since we edit in context via haxcms, though obviously this should work and needs fixed)

**Comment by rickhumphries** [comment]
Yeh I'll DM the raw HTML now. That dom exception error does show on every single one of our pages though - even the ones where this isn't an issue

**Comment by rickhumphries** [comment]
Think I've narrowed down the issue here to a custom `<div>` wrapper we were using so I'll close this for now.
