### ISSUE TITLE
[elmsln] Unable to add new service to existing course

### ISSUE THREAD

**Issue by rickhumphries** [elmsln/issues#967]
I've tried to add a new discussions service to an existing course but there doesn't seem to be a method to do this through the UI on CIS anymore. 
The links on this page now no longer exist - https://online.xyz.co.uk/elmscourse/service-instances
And clicking the button through the lrnapp courses page doesn't seem to do anything:
![image](https://user-images.githubusercontent.com/4973810/159971531-b59b8cf1-afeb-48da-a275-259758855275.png)

**Comment by btopro** [comment]
would need error messages or something. Haven't supported discuss / made any changes to those things (or the CIS UI adding this) in a long time. my guess is that the button isn't clickable for lack of supporting it in the past.

**Comment by rickhumphries** [comment]
I'd probably say you're right that the button just isn't clickable. When I press it the dialog closes but nothing else happens to suggest a process is going on so I doubt there'd be any error messages.

**Comment by rickhumphries** [comment]
What's the alternative way you would do this? Like, if you wanted to add Studio to an existing course?

**Comment by btopro** [comment]
This will require a new build to be generated because of the nature of the problem. It's related to API changes in simple-modal a year or so ago. Was able to fix in lrnwebcomponents but it wont make it into a build until around May most likely as we weren't planning to do an April release and May is target for some other apps that leverage the same pipeline.

As for alternative, maybe there's a drush command to do it but I forget. We effectively haven't been able to add courses or systems for a few months but we basically just maintain things in that setup as opposed to move on with it. Pandemic slowed course development of new courses and only been focused on existing so never noticed these broke.

**Comment by btopro** [comment]
![image](https://user-images.githubusercontent.com/329735/159999685-140d27c2-09e1-4a15-b392-3a15ab4291f9.png)

`drush @online cis-si` with some parameters should do it in the meantime. It runs the same calls that clicking that button taps (been a hot 5+ years since I ran it tho so guessing a bit :) )

**Comment by btopro** [comment]
Release 1.5.1 this now will create the service / kick things off to accomplish it
